# Generated by Django 4.1 on 2023-02-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsheet',
            name='sheet',
        ),
        migrations.AddField(
            model_name='uploadsheet',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='OrgDash/uploads/'),
        ),
    ]
