# Generated by Django 4.1 on 2023-02-26 20:29

import OrgDash.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0026_alter_player_unique_together'),
        ('OrgDash', '0002_remove_uploadsheet_sheet_uploadsheet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsheet',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='OrgDash/uploads/', validators=[OrgDash.models.validate_sheet_only]),
        ),
        migrations.CreateModel(
            name='AutoRecurringSkate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_until_next', models.IntegerField(default=0, max_length=3)),
                ('send_invites_days_before', models.IntegerField(default=1, max_length=3)),
                ('send_invites_time', models.TimeField()),
                ('send_rosters_hours_before', models.IntegerField(default=1, max_length=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickuphockey.skate')),
            ],
        ),
    ]
