# Generated by Django 4.1 on 2023-02-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0003_alter_uploadsheet_file_autorecurringskate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorecurringskate',
            name='days_until_next',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='autorecurringskate',
            name='send_invites_days_before',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='autorecurringskate',
            name='send_rosters_hours_before',
            field=models.IntegerField(default=1),
        ),
    ]
