# Generated by Django 4.1 on 2023-02-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0004_alter_autorecurringskate_days_until_next_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorecurringskate',
            name='frequency',
            field=models.CharField(choices=[('Every Week', 'Every Week'), ('Every Two Weeks', 'Every Two Weeks'), ('Every Month', 'Every Month'), ('Custom', 'Custom')], default='Every Week', max_length=256),
        ),
    ]
