# Generated by Django 4.1 on 2023-02-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0005_autorecurringskate_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorecurringskate',
            name='frequency',
            field=models.CharField(choices=[(7, 'Every Week'), (14, 'Every Two Weeks'), ('Every Month', 'Every Month'), ('Custom', 'Custom')], default='Every Week', max_length=256),
        ),
    ]
