# Generated by Django 4.1 on 2023-03-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0006_alter_autorecurringskate_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorecurringskate',
            name='frequency',
            field=models.CharField(choices=[('Every Week', 'Every Week'), ('Every Two Weeks', 'Every Two Weeks'), ('Every Month', 'Every Month'), ('Custom', 'Custom')], default='Every Week', max_length=256),
        ),
    ]
