# Generated by Django 4.1 on 2023-03-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0008_invitation_player_playergroup_skate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default="You're Invited!", max_length=1500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrgDash.skate')),
                ('guests', models.ManyToManyField(to='OrgDash.player')),
            ],
        ),
    ]
