# Generated by Django 4.1 on 2023-03-13 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0009_invitelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skate',
            name='finalize_event_datetime',
        ),
        migrations.RemoveField(
            model_name='skate',
            name='send_invites_datetime',
        ),
        migrations.AddField(
            model_name='skate',
            name='finalize_event_hours_before',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='skate',
            name='group_to_invite',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='OrgDash.playergroup'),
        ),
        migrations.AddField(
            model_name='skate',
            name='send_invite_days_before',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='skate',
            name='frequency',
            field=models.IntegerField(blank=True, choices=[(7, 'Every Week'), (14, 'Every Two Weeks')], default=7),
        ),
    ]
