# Generated by Django 4.1 on 2023-03-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0010_remove_skate_finalize_event_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergroup',
            name='slug',
        ),
        migrations.AlterField(
            model_name='skate',
            name='group_to_invite',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.CASCADE, to='OrgDash.playergroup'),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='OrgDash.skate')),
                ('guests', models.ManyToManyField(to='OrgDash.player')),
            ],
        ),
    ]
