# Generated by Django 4.1 on 2023-03-18 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0011_remove_playergroup_slug_alter_skate_group_to_invite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skate',
            name='group_to_invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrgDash.playergroup'),
        ),
    ]
