# Generated by Django 4.1 on 2023-03-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0012_alter_skate_group_to_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrgDash.skate')),
                ('light_team', models.ManyToManyField(to='OrgDash.player')),
            ],
        ),
        migrations.CreateModel(
            name='DarkTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_team', models.ManyToManyField(to='OrgDash.player')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrgDash.skate')),
            ],
        ),
    ]
