# Generated by Django 4.1 on 2023-03-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0013_lightteam_darkteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='darkteam',
            old_name='dark_team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='lightteam',
            old_name='light_team',
            new_name='team',
        ),
        migrations.AddField(
            model_name='darkteam',
            name='skill',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lightteam',
            name='skill',
            field=models.FloatField(default=0),
        ),
    ]
