# Generated by Django 4.1 on 2023-03-29 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0017_alter_uploadsheet_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadSheet',
        ),
    ]
