# Generated by Django 4.1 on 2023-03-30 00:06

import OrgDash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0018_delete_uploadsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, null=True, upload_to='OrgDash/uploads/', validators=[OrgDash.models.validate_sheet_only])),
            ],
        ),
    ]
