# Generated by Django 4.1 on 2023-03-30 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0019_uploadsheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadSheet',
        ),
    ]
