# Generated by Django 4.1 on 2023-04-01 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0023_goalie'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkteam',
            name='goalie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrgDash.goalie'),
        ),
        migrations.AddField(
            model_name='lightteam',
            name='goalie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrgDash.goalie'),
        ),
    ]
