# Generated by Django 4.1 on 2023-04-02 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OrgDash', '0024_darkteam_goalie_lightteam_goalie'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalie',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
