# Generated by Django 4.1 on 2023-04-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0025_goalie_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalie',
            name='player',
        ),
        migrations.AddField(
            model_name='goalie',
            name='email',
            field=models.EmailField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='goalie',
            name='first_name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='goalie',
            name='last_name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='goalie',
            name='skill',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
