# Generated by Django 4.1 on 2023-04-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0027_remove_goalie_email_remove_goalie_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_goalie',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
