# Generated by Django 4.1 on 2023-04-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0028_player_is_goalie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_goalie',
            new_name='goalie',
        ),
        migrations.RemoveField(
            model_name='darkteam',
            name='goalie',
        ),
        migrations.RemoveField(
            model_name='lightteam',
            name='goalie',
        ),
        migrations.DeleteModel(
            name='Goalie',
        ),
    ]
