# Generated by Django 4.1 on 2023-04-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0030_rename_max_guests_skate_max_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skate',
            name='goalie_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skate',
            name='player_full',
            field=models.BooleanField(default=False),
        ),
    ]
