# Generated by Django 4.1 on 2023-05-01 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0031_skate_goalie_full_skate_player_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkteam',
            name='event',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrgDash.skate'),
        ),
        migrations.AlterField(
            model_name='lightteam',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OrgDash.skate'),
        ),
    ]
