# Generated by Django 4.1 on 2023-05-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0033_skate_goalie_guests_skate_player_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='skate',
            name='already_duplicated',
            field=models.BooleanField(default=False),
        ),
    ]
