# Generated by Django 4.1 on 2023-05-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0034_skate_already_duplicated'),
    ]

    operations = [
        migrations.AddField(
            model_name='skate',
            name='auto_invites_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skate',
            name='auto_rosters_sent',
            field=models.BooleanField(default=False),
        ),
    ]
