# Generated by Django 4.1 on 2023-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrgDash', '0036_skate_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skate',
            name='user_timezone',
            field=models.CharField(default='America/New_York', max_length=100, null=True),
        ),
    ]
