# Generated by Django 4.1 on 2023-05-02 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickteams', '0002_quickbench_created_by_quickdarkteam_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=300)),
                ('skill', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Here', models.BooleanField(default=False, null=True)),
                ('goalie', models.BooleanField(default=False, null=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='quickbench',
            name='bench_members',
            field=models.ManyToManyField(to='quickteams.quickplayer'),
        ),
        migrations.AlterField(
            model_name='quickdarkteam',
            name='team',
            field=models.ManyToManyField(to='quickteams.quickplayer'),
        ),
        migrations.AlterField(
            model_name='quicklightteam',
            name='team',
            field=models.ManyToManyField(to='quickteams.quickplayer'),
        ),
    ]
