# Generated by Django 4.1 on 2023-05-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickteams', '0003_quickplayer_alter_quickbench_bench_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickplayer',
            old_name='Here',
            new_name='here',
        ),
    ]
