# Generated by Django 4.1 on 2023-01-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.DecimalField(decimal_places=1, max_digits=4)),
                ('RSVP', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='James Pijewski', max_length=200)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
