# Generated by Django 4.1 on 2023-01-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0002_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='skate',
            name='participants',
            field=models.ManyToManyField(null=True, to='pickuphockey.player'),
        ),
    ]
