# Generated by Django 4.1 on 2023-01-29 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0003_skate_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skate',
            name='participants',
        ),
        migrations.AddField(
            model_name='skate',
            name='participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pickuphockey.player'),
        ),
    ]
