# Generated by Django 4.1 on 2023-01-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0004_remove_skate_participants_skate_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skate',
            name='participants',
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_invited', models.DateTimeField(auto_now_add=True)),
                ('is_attending', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickuphockey.skate')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickuphockey.player')),
            ],
        ),
        migrations.AddField(
            model_name='skate',
            name='participants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'RSVP': True}, related_name='events', through='pickuphockey.Invitation', to='pickuphockey.player'),
        ),
    ]
