# Generated by Django 4.1 on 2023-01-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0005_remove_skate_participants_invitation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='RSVP',
        ),
        migrations.AlterField(
            model_name='skate',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='Player', through='pickuphockey.Invitation', to='pickuphockey.player'),
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.ManyToManyField(to='pickuphockey.invitation')),
            ],
        ),
    ]
