# Generated by Django 4.1 on 2023-02-09 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickuphockey', '0009_alter_player_user_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skate',
            name='host',
        ),
        migrations.AddField(
            model_name='skate',
            name='host',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
