# Generated by Django 4.1 on 2023-02-11 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickuphockey', '0011_skate_date_alter_skate_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skate',
            name='host',
        ),
        migrations.AddField(
            model_name='skate',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
