# Generated by Django 4.1 on 2023-02-12 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickuphockey', '0012_remove_skate_host_skate_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='user',
        ),
        migrations.AddField(
            model_name='invitation',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GuestList',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
