# Generated by Django 4.1 on 2023-02-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0013_remove_host_user_invitation_host_delete_guestlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
