# Generated by Django 4.1 on 2023-02-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0016_guestlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestList',
        ),
    ]
