# Generated by Django 4.1 on 2023-02-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0018_invitation_will_you_attend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='will_you_attend',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Waitlist', 'Put me on the waitlist')], default='No', max_length=256),
        ),
    ]
