# Generated by Django 4.1 on 2023-02-22 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0020_remove_skate_participants_skate_max_guests'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('guest', 'event')},
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='is_attending',
        ),
    ]
