# Generated by Django 4.1 on 2023-02-22 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0022_group_playergroup_group_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='players',
            new_name='players_list',
        ),
        migrations.RenameField(
            model_name='playergroup',
            old_name='object',
            new_name='Player',
        ),
    ]
