# Generated by Django 4.1 on 2023-02-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0023_rename_players_group_players_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_attending',
            field=models.BooleanField(default=False),
        ),
    ]
