# Generated by Django 4.1 on 2023-02-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0024_invitation_is_attending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='is_attending',
        ),
    ]
