# Generated by Django 4.1 on 2023-02-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0026_alter_player_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='skate',
            name='recurring_event',
            field=models.BooleanField(default=False),
        ),
    ]
