# Generated by Django 4.1 on 2023-03-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0027_skate_recurring_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='skate',
            name='finalize_event_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='skate',
            name='frequency',
            field=models.CharField(choices=[('Every Week', 'Every Week'), ('Every Two Weeks', 'Every Two Weeks'), ('Every Month', 'Every Month'), ('Custom', 'Custom')], default='Every Week', max_length=256),
        ),
        migrations.AddField(
            model_name='skate',
            name='send_invites_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
