# Generated by Django 4.1 on 2023-03-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0031_playergroup_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergroup',
            name='slug',
            field=models.SlugField(default='group-name'),
        ),
    ]
