# Generated by Django 4.1 on 2023-03-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickuphockey', '0032_playergroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergroup',
            name='slug',
            field=models.SlugField(default='group-name', unique=True),
        ),
    ]
